# Generated by Django 4.2.7 on 2023-11-21 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0006_alter_food_price_alter_orderdetails_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
