# Generated by Django 4.2.7 on 2023-11-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0007_remove_orderdetails_customer_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='Customer_Name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
