# Generated by Django 4.2.7 on 2023-11-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0008_orderdetails_customer_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
    ]
