# Generated by Django 4.2.7 on 2023-11-27 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0011_alter_employee_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,10}$')]),
        ),
    ]
