# Generated by Django 4.2.7 on 2023-11-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0012_alter_employee_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ID_Number',
            field=models.CharField(max_length=50),
        ),
    ]
